- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/dao/dto/GroupsDto.java
Добавила сущность "GroupsDto" в ttmanager.
> [CS-B-015]

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/ru/cfuv/cfuvscheduling/LoginActivity.kt
- android/app/src/main/res/values/strings.xml
No logics for now (no backend = no bother)
> [CS-M-030] Initial LoginActivity layout

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/ru/cfuv/cfuvscheduling/LoginActivity.kt
- android/app/src/main/res/values/strings.xml
> [CS-M-032] Add register screen layout

- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/bom/RefClassTypeBom.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/controller/RefClassTypeController.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/converter/RefClassTypeConverter.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassTypeService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/RefClassTypeDao.java
Реализовала получение списка всех типов занятий.
> [CS-B-026]

- android/app/src/main/java/ru/cfuv/cfuvscheduling/DummyClassBom.kt
- android/app/src/main/java/ru/cfuv/cfuvscheduling/TimetableComposable.kt
Добавил сущность расписания для передачи его в функцию в качестве параметра (оттуда берутся данные для элементов).
Создал следующиие функции:
- TimetableScreen - выводит весь экран расписания
- ClassItem - выводит информацию о занятии (время, шифр, аудитория и т.д.)
- ClassInfoItem - выводит блок с информацией о занятии (шифр предмета, ФИО преподавателя, аудитория) (часть ClassItem)
- ClassNumberItem - выводит номер занятия и промежуток времени (часть ClassItem)
> [CS-M-033] Создать макет страницы расписания

- server/auth/pom.xml
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/bom/UserBom.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/conntroller/JwtController.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/converter/UserConverter.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/dao/UserDao.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/jwt/JwtUtils.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/service/AuthService.java
- server/auth/src/main/resources/application.yml
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/dto/UserDto.java
Реализован метод генерации и чтения JWT-токена.
> CS-B-016 | Реализовать метод генерации и чтения JWT-токена

- server/admin/pom.xml
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/AdminApplication.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/connector/AuthConnector.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/controller/RefClassTypeController.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/converter/RefClassTypeConverter.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassTypeService.java
- server/admin/src/main/resources/application.yml
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/conntroller/AuthController.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/converter/UserConverter.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/service/AuthService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/UserBom.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/UserRoles.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/ReferenceDao.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/exception/AlreadyExistsException.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/exception/GlobalControllerExceptionHandler.java
commons:
- Добавлено новое исключение AlreadyExistsException. Используется для обозначения того, что объект с таким названием (или группой полей с такими же значениями) уже существует.
- ReferenceDao. findByName() теперь возвращает Optional.
- UserBom перемещен из модуля авторизации в общий модуль.
- Создано перечисление ролей.
auth:
- Создан AuthController с методом, который возвращает объект текущего авторизованного пользователя (определяет по токену, который приходит в заголовке).
admin:
- Добавлен зависимость spring-cloud-starter-openfeign.
- Добавлена запись в конфиге для обозначения пути к микросервису авторизации (для коннектора).
- Добавлен коннектор для обращения к модулю авторизации из модуля администрирования (AuthConnector).
- В RefClassTypeConverter добавлен метод toDto().
- …
> [CS-B-041]

- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/bom/AccountForm.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/bom/AccountResponse.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/conntroller/AuthController.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/converter/UserConverter.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/dao/UserRolesDao.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/service/AuthService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/dto/UserDto.java
Реализовала запрос за регистрацию пользователя.
> [CS-B-018]

- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/dto/RefClassDurationsDto.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/bom/RefClassDurationsBom.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/controller/RefClassDurationsController.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/converter/RefClassDurationsConverter.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/dao/RefClassDurationsDao.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/service/RefClassDurationsService.java
Реализовала получение списка номеров пар.
> [CS-B-025]

- server/admin/pom.xml
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/AdminApplication.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/service/AuthService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/UserBom.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/UserDao.java
- server/pom.xml
- server/tt-manager/pom.xml
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/TtManagerApplication.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/connector/AuthConnector.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/controller/ClassController.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/controller/UserValidator.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/dao/ClassDao.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/dao/dto/ClassDto.java
- server/tt-manager/src/main/java/ru/cfuv/cfuvscheduling/ttmanager/service/ClassService.java
- server/tt-manager/src/main/resources/application.yml
Переменная spring-cloud.version перенесена в родительский pom.xml
commons:
- UserDao перенесен в данный модуль
- UserBom добавлен метод isTeacher
auth:
- Создан AuthController с методом, который возвращает объект текущего авторизованного пользователя (определяет по токену, который приходит в заголовке).
tt-manager:
- Добавлены зависимости для Feign Client
- Добавлены параметры конфигурации для AuthConnector
- Созданы ClassController, ClassService, ClassDao
- Созданы AuthConnector и UserValidator (с методом validateUserAsTeacher)
- Реализован метод добавления комментария под занятие
> [CS-B-021]

- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/conntroller/TeacherController.java
- server/auth/src/main/java/ru/cfuv/cfuvscheduling/auth/service/TeacherService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/UserBom.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/converter/UserConverter.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/UserDao.java
Отрефакторил бом, дто и конвертер пользователя
В сервисе авторизации добавил TeacherController, TeacherService Реализовал логику получения списка преподавателей (доступно только админу)
> [CS-B-024]

- server/auth/src/main/resources/application.yml
- server/auth/src/main/resources/data.sql
Change hbm2ddl.auto to create to pull initial data from import.sql
> [CS-B-044] Add initial data for roles DB table

- server/tt-manager/src/main/resources/application.yml
- server/tt-manager/src/main/resources/data.sql
Add options to always initialize database using Spring JDBC
> [CS-B-045] Add initial data for class types DB table

- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/controller/RefClassDurationsController.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassDurationsService.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/RefClassDurationsBom.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/converter/RefClassDurationsConverter.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/dto/RefClassDurationsDto.java
Реализовала логику добавления записи в таблицу с расписанием пар.
> [CS-B-036]

- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/bom/UserBom.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/converter/UserConverter.java
- server/commons/src/main/java/ru/cfuv/cfuvscheduling/commons/dao/dto/UserDto.java
Добавлены поля ФИО для пользователя
> [CS-B-049]

- server/admin/Dockerfile
- server/admin/src/main/resources/application.yml
- server/auth/Dockerfile
- server/auth/src/main/resources/application.yml
- server/docker-compose.yml
- server/tt-manager/Dockerfile
- server/tt-manager/src/main/resources/application.yml
Wrap micro-services in docker containers
> [CS-B-048] Create Docker Compose application

- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/controller/GroupsController.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/GroupsService.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassTypeService.java
Реализовал метод удаления группы
> [CS-B-040]

- server/auth/pom.xml
- server/auth/src/test/java/ru/cfuv/cfuvscheduling/auth/bdd/AuthTestContext.java
- server/auth/src/test/java/ru/cfuv/cfuvscheduling/auth/bdd/CucumberIntegrationTest.java
- server/auth/src/test/java/ru/cfuv/cfuvscheduling/auth/bdd/given/UserAuthorizationGiven.java
- server/auth/src/test/java/ru/cfuv/cfuvscheduling/auth/bdd/then/UserAuthorizationThen.java
- server/auth/src/test/java/ru/cfuv/cfuvscheduling/auth/bdd/when/UserAuthorizationWhen.java
- server/auth/src/test/resources/application.yml
- server/auth/src/test/resources/bdd/features/authorization.feature
Команда для запуска интеграционных тестов:
`mvn -pl auth -am clean test -Dcucumber.features=src/test/resources/bdd/features/`
> [CS-B-053] Добавил интеграционные тесты для авторизации

- server/auth/pom.xml
Теперь можно запускать отдельно только юнит тесты или только интеграционные
`mvn -pl auth -am clean test -P unit` - только юнит
`mvn -pl auth -am clean test -P integration` - только интеграционные
> [CS-B-053] Настроил профили для запусков отдельных видов тестов

- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/service/RefClassTypeServiceTest.java
Написал UNIT тесты для RefClassTypeService
> [CS-B-054]

- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/controller/RefClassDurationsController.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/dao/RefClassDurationsDao.java
- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassDurationsService.java
Реализовала логику изменения записи из таблицы расписания звонков.
> [CS-B-037]

- server/admin/pom.xml
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/AdminTestContext.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/AdminTestUtils.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/CucumberIntegrationTest.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/given/DummyTestGiven.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/then/DummyTestThen.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/bdd/when/DummyTestWhen.java
- server/admin/src/test/resources/application.yml
- server/admin/src/test/resources/bdd/features/dummy.feature
Добавил тестовые степы для примера
Добавил тестовые сценарии с демонстрацией возможностей (рабочий сценарий; сценарий, помеченный аннотацией @Bug, который не будет запускаться)
> [integration] Подключил cucumber в модуле администрирования

- server/admin/src/main/java/ru/cfuv/cfuvscheduling/admin/service/RefClassDurationsService.java
- server/admin/src/test/java/ru/cfuv/cfuvscheduling/admin/service/RefClassDurationsServiceTest.java
- server/auth/pom.xml
Написала unit-тесты для RefClassDurationsService.
> [CS-B-067]
